# 영혼 교체 타이머는 {interval-seconds}초 마다 {probability}의 확률로 작동합니다.
timer:
  interval-seconds: 30
  probability: 0.33

change-on-damaged:
  # 플레이어 피격시 영혼 교체를 실행할 지 결정합니다.
  enabled: false
  # 피격 당한 플레이어를 공지할 지 결정합니다.
  notify-damagee: false

damage-share:
  # 대미지 공유를 활성화할 지 결정합니다.
  enabled: false
  # 공유될 대미지에 곱해지는 계수입니다. (0 ~ 1의 실수)
  rate: 1.0

# 영혼 교체 공지의 위치를 바꾸거나 비활성화할 수 있습니다. (TITLE, CHAT, NONE)
notification: "TITLE"
